// <auto-generated />
using System;
using FruitFly.Repository.Configurations;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace FruitFly.Repository.Migrations
{
    [DbContext(typeof(FruitFlyContext))]
    [Migration("20200502121244_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("FruitFly.Repository.Models.Heatmap", b =>
                {
                    b.Property<int>("HeatmapID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ReferencepointId")
                        .HasColumnType("int");

                    b.Property<int?>("ReferencepointId1")
                        .HasColumnType("int");

                    b.HasKey("HeatmapID");

                    b.HasIndex("ReferencepointId");

                    b.HasIndex("ReferencepointId1")
                        .IsUnique()
                        .HasFilter("[ReferencepointId1] IS NOT NULL");

                    b.ToTable("Heatmaps");

                    b.HasData(
                        new
                        {
                            HeatmapID = 1,
                            ReferencepointId = 1
                        },
                        new
                        {
                            HeatmapID = 2,
                            ReferencepointId = 2
                        },
                        new
                        {
                            HeatmapID = 3,
                            ReferencepointId = 3
                        },
                        new
                        {
                            HeatmapID = 4,
                            ReferencepointId = 4
                        });
                });

            modelBuilder.Entity("FruitFly.Repository.Models.Referencepoint", b =>
                {
                    b.Property<int>("ReferencepointId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Category")
                        .HasColumnType("int");

                    b.Property<int>("RSSI1")
                        .HasColumnType("int");

                    b.Property<int>("RSSI2")
                        .HasColumnType("int");

                    b.Property<int>("RSSI3")
                        .HasColumnType("int");

                    b.Property<int>("X")
                        .HasColumnType("int");

                    b.Property<int>("Y")
                        .HasColumnType("int");

                    b.HasKey("ReferencepointId");

                    b.ToTable("Referencepoints");

                    b.HasData(
                        new
                        {
                            ReferencepointId = 1,
                            Category = 1,
                            RSSI1 = 79,
                            RSSI2 = 25,
                            RSSI3 = 75,
                            X = 1,
                            Y = 1
                        },
                        new
                        {
                            ReferencepointId = 2,
                            Category = 8,
                            RSSI1 = 86,
                            RSSI2 = 12,
                            RSSI3 = 70,
                            X = 1,
                            Y = 2
                        },
                        new
                        {
                            ReferencepointId = 3,
                            Category = 8,
                            RSSI1 = 61,
                            RSSI2 = 88,
                            RSSI3 = 5,
                            X = 2,
                            Y = 1
                        },
                        new
                        {
                            ReferencepointId = 4,
                            Category = 14,
                            RSSI1 = 78,
                            RSSI2 = 34,
                            RSSI3 = 36,
                            X = 2,
                            Y = 2
                        });
                });

            modelBuilder.Entity("FruitFly.Repository.Models.Heatmap", b =>
                {
                    b.HasOne("FruitFly.Repository.Models.Referencepoint", "Referencepoint")
                        .WithMany()
                        .HasForeignKey("ReferencepointId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FruitFly.Repository.Models.Referencepoint", null)
                        .WithOne("Heatmap")
                        .HasForeignKey("FruitFly.Repository.Models.Heatmap", "ReferencepointId1");
                });
#pragma warning restore 612, 618
        }
    }
}
